### ISSUE TITLE
Channel.invoke_shell() failed with latest version of Openssh

### ISSUE THREAD

**Issue by sureshkotapydev** [PowerShell/Win32-OpenSSH#1473]
**Troubleshooting steps**
https://github.com/PowerShell/Win32-OpenSSH/wiki/Troubleshooting-Steps

**Terminal issue? please go through wiki**
https://github.com/PowerShell/Win32-OpenSSH/wiki/TTY-PTY-support-in-Windows-OpenSSH

Please answer the following

**"OpenSSH for Windows" version**
 `8.0.0.0`
 
**Server OperatingSystem**
 `Windows Server 2016 Standard Evaluation`

**Client OperatingSystem**
`CentOS Linux release 7.6.1810 (Core)`

**What is failing**
```
Python 3.6.7 (default, Dec  5 2018, 15:02:05)
[GCC 4.8.5 20150623 (Red Hat 4.8.5-36)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import paramiko
>>> cl = paramiko.SSHClient()
>>> cl.set_missing_host_key_policy(paramiko.AutoAddPolicy())
>>> cl.connect(hostname=hostname, username=username, password=password)
>>> ch = cl.get_transport().open_session()
>>> ch.invoke_shell()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/myenv/lib64/python3.6/site-packages/paramiko/channel.py", line 72, in _check
    return func(self, *args, **kwds)
  File "/home/myenv/lib64/python3.6/site-packages/paramiko/channel.py", line 230, in invoke_shell
    self._wait_for_event()
  File "/home/myenv/lib64/python3.6/site-packages/paramiko/channel.py", line 1208, in _wait_for_event
    raise e
paramiko.ssh_exception.SSHException: Channel closed.
```
**Expected output**
`ch.invoke_shell()` should be successful. This works in `v7.7.2.0p1-Beta` and below versions.

**Actual output**
`paramiko.ssh_exception.SSHException: Channel closed`

**Comment by manojampalam** [comment]
Can you share server side traces in both success (7.7.2.0) and failure (8.0.0.0) cases ?

**Comment by sureshkotapydev** [comment]
**v8.0.0.0p1-Beta Server log**
```
4308 2019-10-11 11:17:27.585 debug1: Bind to port 22 on ::.
4308 2019-10-11 11:17:27.586 Server listening on :: port 22.
4308 2019-10-11 11:17:27.586 debug1: Bind to port 22 on 0.0.0.0.
4308 2019-10-11 11:17:27.586 Server listening on 0.0.0.0 port 22.
5088 2019-10-11 11:17:51.060 debug1: inetd sockets after dupping: 4, 4
5088 2019-10-11 11:17:51.060 Connection from x.x.x.x port 40556 on x.x.x.x port 22
5088 2019-10-11 11:17:51.060 debug1: Local version string SSH-2.0-OpenSSH_for_Windows_8.0
5088 2019-10-11 11:17:51.060 debug1: Remote protocol version 2.0, remote software version paramiko_2.4.2
5088 2019-10-11 11:17:51.060 debug1: no match: paramiko_2.4.2
5088 2019-10-11 11:17:51.147 debug1: list_hostkey_types: rsa-sha2-512,rsa-sha2-256,ssh-rsa,ecdsa-sha2-nistp256,ssh-ed25519 [preauth]
5088 2019-10-11 11:17:51.147 debug1: SSH2_MSG_KEXINIT sent [preauth]
5088 2019-10-11 11:17:51.148 debug1: SSH2_MSG_KEXINIT received [preauth]
5088 2019-10-11 11:17:51.148 debug1: kex: algorithm: ecdh-sha2-nistp256 [preauth]
5088 2019-10-11 11:17:51.148 debug1: kex: host key algorithm: ssh-ed25519 [preauth]
5088 2019-10-11 11:17:51.148 debug1: kex: client->server cipher: aes128-ctr MAC: hmac-sha2-256 compression: none [preauth]
5088 2019-10-11 11:17:51.148 debug1: kex: server->client cipher: aes128-ctr MAC: hmac-sha2-256 compression: none [preauth]
5088 2019-10-11 11:17:51.148 debug1: expecting SSH2_MSG_KEX_ECDH_INIT [preauth]
5088 2019-10-11 11:17:51.155 debug1: rekey out after 4294967296 blocks [preauth]
5088 2019-10-11 11:17:51.155 debug1: SSH2_MSG_NEWKEYS sent [preauth]
5088 2019-10-11 11:17:51.155 debug1: expecting SSH2_MSG_NEWKEYS [preauth]
5088 2019-10-11 11:17:51.157 debug1: SSH2_MSG_NEWKEYS received [preauth]
5088 2019-10-11 11:17:51.157 debug1: rekey in after 4294967296 blocks [preauth]
5088 2019-10-11 11:17:51.157 debug1: KEX done [preauth]
5088 2019-10-11 11:17:51.208 debug1: userauth-request for user Administrator service ssh-connection method password [preauth]
5088 2019-10-11 11:17:51.208 debug1: attempt 0 failures 0 [preauth]
5088 2019-10-11 11:17:51.213 debug1: user administrator matched group list administrators at line 87
5088 2019-10-11 11:17:51.219 Accepted password for Administrator from x.x.x.x port 40556 ssh2
5088 2019-10-11 11:17:51.219 debug1: monitor_child_preauth: Administrator has been authenticated by privileged process
5088 2019-10-11 11:17:51.228 debug1: monitor_read_log: child log fd closed
5088 2019-10-11 11:17:51.268 User child is on pid 2704
2704 2019-10-11 11:17:51.294 debug1: user administrator matched group list administrators at line 87
2704 2019-10-11 11:17:51.296 debug1: rekey in after 4294967296 blocks
2704 2019-10-11 11:17:51.296 debug1: rekey out after 4294967296 blocks
2704 2019-10-11 11:17:51.296 debug1: ssh_packet_set_postauth: called
2704 2019-10-11 11:17:51.296 debug1: active: key options: agent-forwarding port-forwarding pty user-rc x11-forwarding
2704 2019-10-11 11:17:51.296 debug1: Entering interactive session for SSH2.
2704 2019-10-11 11:17:51.296 debug1: server_init_dispatch
2704 2019-10-11 11:17:56.151 debug1: server_input_channel_open: ctype session rchan 0 win 2097152 max 32768
2704 2019-10-11 11:17:56.151 debug1: input_session_request
2704 2019-10-11 11:17:56.152 debug1: channel 0: new [server-session]
2704 2019-10-11 11:17:56.152 debug1: session_new: session 0
2704 2019-10-11 11:17:56.152 debug1: session_open: channel 0
2704 2019-10-11 11:17:56.152 debug1: session_open: session 0: link with channel 0
2704 2019-10-11 11:17:56.152 debug1: server_input_channel_open: confirm session
2704 2019-10-11 11:17:59.917 debug1: server_input_channel_req: channel 0 request shell reply 1
2704 2019-10-11 11:17:59.917 debug1: session_by_channel: session 0 channel 0
2704 2019-10-11 11:17:59.917 debug1: session_input_channel_req: session 0 req shell
2704 2019-10-11 11:17:59.917 Starting session: shell for administrator from x.x.x.x port 40556 id 0
2704 2019-10-11 11:17:59.969 debug1: session_by_channel: session 0 channel 0
2704 2019-10-11 11:17:59.969 debug1: session_close_by_channel: channel 0 child 0
2704 2019-10-11 11:17:59.969 Close session: user administrator from x.x.x.x port 40556 id 0
2704 2019-10-11 11:17:59.969 debug1: channel 0: free: server-session, nchannels 1
```

**v7.7.2.0p1-Beta Server log**
```
6956 2019-10-11 11:28:30.873 debug1: Bind to port 22 on ::.
6956 2019-10-11 11:28:30.873 Server listening on :: port 22.
6956 2019-10-11 11:28:30.873 debug1: Bind to port 22 on 0.0.0.0.
6956 2019-10-11 11:28:30.873 Server listening on 0.0.0.0 port 22.
8144 2019-10-11 11:28:56.957 debug1: inetd sockets after dupping: 3, 3
8144 2019-10-11 11:28:56.957 Connection from x.x.x.x port 40754 on x.x.x.x port 22
8144 2019-10-11 11:28:56.957 debug1: Client protocol version 2.0; client software version paramiko_2.4.2
8144 2019-10-11 11:28:56.957 debug1: no match: paramiko_2.4.2
8144 2019-10-11 11:28:56.957 debug1: Local version string SSH-2.0-OpenSSH_for_Windows_7.7
8144 2019-10-11 11:28:57.178 debug1: list_hostkey_types: ssh-rsa,rsa-sha2-512,rsa-sha2-256,ecdsa-sha2-nistp256,ssh-ed25519 [preauth]
8144 2019-10-11 11:28:57.178 debug1: SSH2_MSG_KEXINIT sent [preauth]
8144 2019-10-11 11:28:57.178 debug1: SSH2_MSG_KEXINIT received [preauth]
8144 2019-10-11 11:28:57.178 debug1: kex: algorithm: ecdh-sha2-nistp256 [preauth]
8144 2019-10-11 11:28:57.178 debug1: kex: host key algorithm: ssh-ed25519 [preauth]
8144 2019-10-11 11:28:57.179 debug1: kex: client->server cipher: aes128-ctr MAC: hmac-sha2-256 compression: none [preauth]
8144 2019-10-11 11:28:57.179 debug1: kex: server->client cipher: aes128-ctr MAC: hmac-sha2-256 compression: none [preauth]
8144 2019-10-11 11:28:57.179 debug1: expecting SSH2_MSG_KEX_ECDH_INIT [preauth]
8144 2019-10-11 11:28:57.372 debug1: rekey after 4294967296 blocks [preauth]
8144 2019-10-11 11:28:57.372 debug1: SSH2_MSG_NEWKEYS sent [preauth]
8144 2019-10-11 11:28:57.372 debug1: expecting SSH2_MSG_NEWKEYS [preauth]
8144 2019-10-11 11:28:57.374 debug1: SSH2_MSG_NEWKEYS received [preauth]
8144 2019-10-11 11:28:57.374 debug1: rekey after 4294967296 blocks [preauth]
8144 2019-10-11 11:28:57.374 debug1: KEX done [preauth]
8144 2019-10-11 11:28:57.425 debug1: userauth-request for user Administrator service ssh-connection method password [preauth]
8144 2019-10-11 11:28:57.425 debug1: attempt 0 failures 0 [preauth]
8144 2019-10-11 11:28:57.428 debug1: user Administrator matched group list administrators at line 87
8144 2019-10-11 11:28:57.433 Accepted password for Administrator from x.x.x.x port 40754 ssh2
8144 2019-10-11 11:28:57.433 debug1: monitor_child_preauth: Administrator has been authenticated by privileged process
8144 2019-10-11 11:28:57.435 debug1: monitor_read_log: child log fd closed
8144 2019-10-11 11:28:57.472 User child is on pid 3628
3628 2019-10-11 11:28:57.489 debug1: user administrator matched group list administrators at line 87
3628 2019-10-11 11:28:57.489 debug1: rekey after 4294967296 blocks
3628 2019-10-11 11:28:57.489 debug1: rekey after 4294967296 blocks
3628 2019-10-11 11:28:57.489 debug1: ssh_packet_set_postauth: called
3628 2019-10-11 11:28:57.491 debug1: active: key options: agent-forwarding port-forwarding pty user-rc x11-forwarding
3628 2019-10-11 11:28:57.491 debug1: Entering interactive session for SSH2.
3628 2019-10-11 11:28:57.491 debug1: server_init_dispatch
3628 2019-10-11 11:29:00.749 debug1: server_input_channel_open: ctype session rchan 0 win 2097152 max 32768
3628 2019-10-11 11:29:00.749 debug1: input_session_request
3628 2019-10-11 11:29:00.749 debug1: channel 0: new [server-session]
3628 2019-10-11 11:29:00.750 debug1: session_new: session 0
3628 2019-10-11 11:29:00.750 debug1: session_open: channel 0
3628 2019-10-11 11:29:00.750 debug1: session_open: session 0: link with channel 0
3628 2019-10-11 11:29:00.750 debug1: server_input_channel_open: confirm session
3628 2019-10-11 11:29:04.457 debug1: server_input_channel_req: channel 0 request shell reply 1
3628 2019-10-11 11:29:04.457 debug1: session_by_channel: session 0 channel 0
3628 2019-10-11 11:29:04.457 debug1: session_input_channel_req: session 0 req shell
3628 2019-10-11 11:29:04.457 Starting session: shell for administrator from x.x.x.x port 40754 id 0
3628 2019-10-11 11:29:04.458 debug1: Executing command: "c:\\windows\\system32\\cmd.exe" with no pty
```

The difference I see is,
```
3628 2019-10-11 11:29:04.458 debug1: Executing command: "c:\\windows\\system32\\cmd.exe" with no pty
```
is not there in latest version but raises `paramiko.ssh_exception.SSHException: Channel closed` when executed `ch.invoke_shell()`

**Comment by sureshkotapydev** [comment]
@manojampalam 
Was the above information helpful? or Do you need more info?

**Comment by maertendMSFT** [comment]
Can you try the latest version and provide the logs?  Thanks.
