### ISSUE TITLE
Win32-OpenSSH not working with Jenkins SSH Slaves Plugin

### ISSUE THREAD

**Issue by larsimmisch** [PowerShell/Win32-OpenSSH#927]
**"OpenSSH for Windows" version**
 `0.0.21.0`
 
**Server OperatingSystem**
 `Windows 10 Enterprise`

**Client OperatingSystem**
Jenkins 2.73.2/SSH Slaves plugin 1.22 

https://wiki.jenkins.io/display/JENKINS/SSH+Slaves+plugin

The Jenkins SH slaves plugin does not interoperate with the Jenkins SSH Slaves plugin. Logs indicate that the openssh server drops the connection unexpectedly. See below.

For a detailed discussion, see https://issues.jenkins-ci.org/browse/JENKINS-42856

```
[03/16/17 14:35:26] [SSH] Opening SSH connection to myserver:22.
[03/16/17 14:35:31] [SSH] Authentication successful.
[03/16/17 14:35:34] [SSH] The remote users environment is:
[03/16/17 14:35:36] [SSH] Starting sftp client.
[03/16/17 14:35:39] [SSH] Copying latest slave.jar...
[03/16/17 14:36:00] [SSH] Copied 717,563 bytes.
Expanded the channel window size to 4MB
[03/16/17 14:36:00] [SSH] Starting slave process: cd "C:\Jenkins" && "C:\Program Files\Java\jre1.8.0_121\bin\java"  -jar slave.jar
<===[JENKINS REMOTING CAPACITY]===><===[JENKINS REMOTING CAPACITY]===>ERROR: Unexpected error in launching a slave. This is probably a bug in Jenkins.
hudson.remoting.RequestAbortedException: java.io.IOException: Unexpected termination of the channel
	at hudson.remoting.Request.abort(Request.java:307)
	at hudson.remoting.Channel.terminate(Channel.java:888)
	at hudson.remoting.SynchronousCommandTransport$ReaderThread.run(SynchronousCommandTransport.java:92)
	at ......remote call to myserver(Native Method)
	at hudson.remoting.Channel.attachCallSiteStackTrace(Channel.java:1537)
	at hudson.remoting.Request.call(Request.java:172)
	at hudson.remoting.Channel.call(Channel.java:821)
	at hudson.slaves.SlaveComputer.setChannel(SlaveComputer.java:516)
	at hudson.slaves.SlaveComputer.setChannel(SlaveComputer.java:389)
	at hudson.plugins.sshslaves.SSHLauncher.startSlave(SSHLauncher.java:989)
	at hudson.plugins.sshslaves.SSHLauncher.access$400(SSHLauncher.java:139)
	at hudson.plugins.sshslaves.SSHLauncher$2.call(SSHLauncher.java:738)
	at hudson.plugins.sshslaves.SSHLauncher$2.call(SSHLauncher.java:719)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
Caused by: java.io.IOException: Unexpected termination of the channel
	at hudson.remoting.SynchronousCommandTransport$ReaderThread.run(SynchronousCommandTransport.java:73)
Caused by: java.io.EOFException
	at java.io.ObjectInputStream$PeekInputStream.readFully(Unknown Source)
	at java.io.ObjectInputStream$BlockDataInputStream.readShort(Unknown Source)
	at java.io.ObjectInputStream.readStreamHeader(Unknown Source)
	at java.io.ObjectInputStream.<init>(Unknown Source)
	at hudson.remoting.ObjectInputStreamEx.<init>(ObjectInputStreamEx.java:48)
	at hudson.remoting.AbstractSynchronousByteArrayCommandTransport.read(AbstractSynchronousByteArrayCommandTransport.java:34)
	at hudson.remoting.SynchronousCommandTransport$ReaderThread.run(SynchronousCommandTransport.java:59)
[03/16/17 14:36:09] Launch failed - cleaning up connection
ERROR: Connection terminated
java.io.IOException: Unexpected termination of the channel
	at hudson.remoting.SynchronousCommandTransport$ReaderThread.run(SynchronousCommandTransport.java:73)
Caused by: java.io.EOFException
	at java.io.ObjectInputStream$PeekInputStream.readFully(Unknown Source)
	at java.io.ObjectInputStream$BlockDataInputStream.readShort(Unknown Source)
	at java.io.ObjectInputStream.readStreamHeader(Unknown Source)
	at java.io.ObjectInputStream.<init>(Unknown Source)
	at hudson.remoting.ObjectInputStreamEx.<init>(ObjectInputStreamEx.java:48)
	at hudson.remoting.AbstractSynchronousByteArrayCommandTransport.read(AbstractSynchronousByteArrayCommandTransport.java:34)
	at hudson.remoting.SynchronousCommandTransport$ReaderThread.run(SynchronousCommandTransport.java:59)
[03/16/17 14:36:09] [SSH] Connection closed.
```

**Comment by bagajjal** [comment]
Please share the sshd_config and sshd.log with DEBUG3 enabled

**Comment by larsimmisch** [comment]
Attached are the log file with DEBUG3 and the configuration .

[sshd.log](https://github.com/PowerShell/Win32-OpenSSH/files/1422011/sshd.log)
[sshd_config.txt](https://github.com/PowerShell/Win32-OpenSSH/files/1422014/sshd_config.txt)

I do have the sneaking suspicion that the far end closes the connection. Have you got any idea where to look on the other side? This may be a bug in the Java SSH libraries, apparently both Trilead SSH and Apache MINA are affected. Over at https://issues.jenkins-ci.org/browse/JENKINS-42856, Stephen Connolly said:

> I spent 3 weeks banging my head against that, it happens with both Trilead SSH and Apache MINA SSH java libraries.

BTW: thank you for this project and your work on it and thank you for doing it out in the open.

**Comment by bagajjal** [comment]
Logs indicate that the connection is teared down by the ssh client..

7292 05:14:37:498 debug1: Executing command: C:\\Program Files\\OpenSSH-Win64\\ssh-shellhost.exe -nopty dHJ1ZQ==
7292 05:14:37:498 debug2: fd 3 setting TCP_NODELAY
7292 05:14:37:498 debug3: fd 10 is O_NONBLOCK
7292 05:14:37:498 debug3: fd 9 is O_NONBLOCK
7292 05:14:37:498 debug3: fd 12 is O_NONBLOCK
7292 05:14:37:498 debug3: send packet: type 99
7292 05:14:37:498 debug3: receive packet: type 96
7292 05:14:37:498 debug2: channel 0: rcvd eof
7292 05:14:37:498 debug2: channel 0: output open -> drain
7292 05:14:37:498 debug2: channel 0: obuf empty
7292 05:14:37:498 debug2: channel 0: close_write
7292 05:14:37:498 debug2: channel 0: output drain -> closed
7292 05:14:37:545 debug2: channel 0: read<=0 rfd 10 len 0
7292 05:14:37:545 debug2: channel 0: read failed
7292 05:14:37:545 debug2: channel 0: close_read
7292 05:14:37:545 debug2: channel 0: input open -> drain
7292 05:14:37:545 debug2: channel 0: ibuf_empty delayed efd 12/(0)
7292 05:14:37:545 debug2: channel 0: read 0 from efd 12
7292 05:14:37:545 debug2: channel 0: closing read-efd 12
7292 05:14:37:545 debug2: channel 0: ibuf empty
7292 05:14:37:545 debug2: channel 0: send eof
7292 05:14:37:545 debug3: send packet: type 96
7292 05:14:37:545 debug2: channel 0: input drain -> closed
7292 05:14:37:545 debug1: Received SIGCHLD.
7292 05:14:37:545 debug1: session_by_pid:

**Comment by manojampalam** [comment]
Reopen if needed. 

It looks like your client is sending the following command to target
cd "/jenkins" && java  -jar slave.jar

Try executing this via ssh.exe and see if its working as expected.
